#services:
#    nginx:
#        build:
#            context: .
#            dockerfile: nginx/Dockerfile
#        ports:
#            - "8080:80"
#        networks:
#            - internal
#        volumes:
#            - ./:/var/www/html/
#        container_name: nginx
#
#    app:
#        restart: always
#        build:
#            context: .
#            dockerfile: Dockerfile
#        networks:
#            - internal
#        volumes:
#            - ./:/var/www/html/
#        container_name: php
#        expose:
#            - "9000"
#
#    mysql:
#        container_name: db
#        restart: always
#        image: mysql:latest
#        platform: linux/x86_64
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_ROOT_PASSWORD: 'root'
#            MYSQL_USER: 'thoriq'
#            MYSQL_PASS: 'password'
#        networks:
#            - internal
#
#networks:
#    internal:
#        driver: bridge

services:
    app:
        build: .
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel-app

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./storage/:/etc/nginx/conf.d/
        networks:
            - laravel-app

    db:
#        image: mysql:latest
#        container_name: db
#        restart: always
#        tty: true
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_ROOT_PASSWORD: 'root'
#            MYSQL_USER: 'thoriq'
#            MYSQL_PASS: 'password'
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
        container_name: db
        restart: always
        image: mysql:latest
        platform: linux/x86_64
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'thoriq'
            MYSQL_PASS: 'password'
        volumes:
            - lbdata:/var/lib/mysql
        networks:
            - laravel-app


networks:
    laravel-app:
        driver: bridge

volumes:
    lbdata:
        driver: local

